### ISSUE TITLE
Support inputs not starting with "0x"

### ISSUE THREAD

**Issue by pirapira** [pirapira/dry-analyzer#2]
Currently the analyzer gives an error when the input does not start with "0x".

**Comment by tomsib2001** [comment]
Would something like [this](https://github.com/pirapira/dry-analyzer/pull/5) work?

EDIT: I was a bit too quick here, fixing.

**Comment by pirapira** [comment]
Ah, yes, I saw the pull-request before finding this comment.  Thanks a lot.

**Comment by pirapira** [comment]
I deployed your changes to the online version.  Much appreciated.
